# Generated by Django 4.2.2 on 2023-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=32)),
                ('Delivery_adress', models.CharField(max_length=11)),
                ('Delivery_method', models.CharField(max_length=12)),
                ('Delivery_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
