# Generated by Django 4.2.3 on 2023-07-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Deliverys',
        ),
    ]
