# Generated by Django 4.2.2 on 2023-06-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=8)),
                ('Email', models.EmailField(max_length=20)),
                ('PassWord', models.CharField(max_length=10)),
            ],
        ),
    ]
