# Generated by Django 4.2.3 on 2023-07-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Venders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venders.venders'),
        ),
    ]
