# Generated by Django 4.2.3 on 2023-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('product_name', models.TextField(max_length=10)),
                ('rating', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('review_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
