# Generated by Django 4.2.2 on 2023-06-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32)),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=4)),
                ('delivery_adress', models.CharField(max_length=33)),
                ('customer_contact', models.CharField(max_length=32)),
                ('payment_status', models.BooleanField()),
                ('order_status', models.CharField(max_length=32)),
                ('payment_method', models.CharField(max_length=32)),
            ],
        ),
    ]
