# Generated by Django 4.2.3 on 2023-07-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_products'),
        ('customer', '0001_initial'),
        ('Delivery', '0002_rename_delivery_deliverys'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='basket',
            field=models.ManyToManyField(to='cart.cart'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.deliverys'),
        ),
    ]
